#!/usr/bin/env bash

#Script transfers a file from our client to a server

# Check if all parameters are provided

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# using scp to Transfer the file
scp -o StrictHostKeyChecking=no -i $SSH_KEY $FILE $USERNAME@$IP:~/

exit 0
