#!/bin/bash

# Install nginx if not already installed
apt-get update
apt-get install -y nginx

# Configure redirection
echo "
server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Additional configuration
    # ...
}" > /etc/nginx/sites-available/default

# Restart nginx
/etc/init.d/nginx reload

# Script complete

